### ISSUE TITLE
Not able to install OpenResty on CentOS 7

### ISSUE THREAD

**Issue by ubercx** [openresty/ngx_openresty#102]
Hi, 
I am trying to install openresty (latest version,  ngx_openresty-1.7.10.1.tar.gz) on centos7. I followed installation instructions on openresty.org but I am not able to get past very first step of configure. 

**My error details are**
 ./configure --with-luajit --with-http_iconv_module -j2
platform: linux (linux)
cp -rp bundle/ build
cd build
cd LuaJIT-2.1-20150223
gmake -j2 TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit
==== Building LuaJIT 2.1.0-alpha ====
gmake -C src
gmake[1]: cc: Command not found
gmake[1]: Entering directory `/home/apache/downloads/ngx_openresty-1.7.10.1/build/LuaJIT-2.1-20150223/src'
gmake[1]: cc: Command not found
gmake[1]: cc: Command not found
gmake[1]: cc: Command not found
gmake[1]: cc: Command not found
gmake[1]: cc: Command not found
Makefile:232: * * * Unsupported target architecture. Stop.
gmake[1]: Leaving directory `/home/apache/downloads/ngx_openresty-1.7.10.1/build/LuaJIT-2.1-20150223/src'
gmake:  [default] Error 2
ERROR: failed to run command: gmake -j2 TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit
-----------------------------------------------------

I googled around, didn't find any good answer.

**Comment by neomantra** [comment]
It looks like you do not have a C development environment installed (although you do have `make`.) 

Here's a random Google'd link about it (not nginx-specific, but Centos/RHEL 7 specific):
http://www.cyberciti.biz/faq/centos-rhel-7-redhat-linux-install-gcc-compiler-development-tools/

**Comment by ubercx** [comment]
Thanks. That was it.
