### ISSUE TITLE
resty socket compatibility with luasocket: settimeout()

### ISSUE THREAD

**Issue by capr** [openresty/ngx_openresty#103]
Hi,

luasocket settimeout() is in seconds, while resty socket settimeout() is in milliseconds; it also doesn't accept a second arg like luasocket's settimeout(). This breaks eg. luasocket's smtp client which sets a default timeout of 60 (which is one minute with luasocket, but 60ms with resty socket).

**Comment by agentzh** [comment]
@capr Not sure which version of LuaSocket you're talking about. At the time I implemented the cosocket I'm pretty sure the LuaSocket version I was looking at is using milliseconds.

Anyway, there is no chance to change cosocket's settimeout() method because that would break backward-compatibility, which is not acceptable.

**Comment by capr** [comment]
Just looked at it now[1][2][3] and it's in seconds, not sure when/if that changed.

I sometimes develop parts of an app outside of openresty so I use luasocket, and this time when I ran the same module in openresty with a settimeout(5) I was getting timeouts on everything, it took me a while to figure it out :)

Anyway, it would be nice if you could publish cosocket, mysql and redis as separate modules. They're useful outside of a web server you know :)

[1] https://github.com/diegonehab/luasocket/blob/master/src/timeout.c#L155
[2] https://github.com/diegonehab/luasocket/blob/master/src/timeout.c#L86
[3] https://github.com/diegonehab/luasocket/blob/master/src/usocket.c#L110

**Comment by agentzh** [comment]
@capr Yeah I understand that motivation and that was why I created the "resty" command-line utility:

https://github.com/openresty/resty-cli

Hopefully you will find it useful.
