### ISSUE TITLE
Issue with "ngx.req.set_uri" in access_by_lua*

### ISSUE THREAD

**Issue by hulu1522** [openresty/ngx_openresty#107]
I am getting this error while trying to set the URI in an `access_by_lua_file` directive:

```
2015/06/22 18:27:59 [error] 3916#0: *214 lua entry thread aborted: runtime error: /usr/local/openresty/work/conf/auth.lua:94: API disabled in the context of access_by_lua*
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /usr/local/openresty/work/conf/auth.lua:94: in function </usr/local/openresty/work/conf/auth.lua:1>, client: 10.130.5.56, server: , request: "GET /?accesskey=abcd HTTP/1.1", host: "10.129.21.233:8080"
```

The official documentation says that it is possible [here](http://wiki.nginx.org/HttpLuaModule#ngx.req.set_uri) but this error says otherwise.  Is there something I am missing?  Thanks for the help.

**Comment by agentzh** [comment]
@hulu1522 `ngx.req.set_uri` is only available in `access_by_lua` when the `jump` argument is not set (or set to false). To quote the documentation you referenced:

"The jump can only be set to true in rewrite_by_lua and rewrite_by_lua_file. Use of jump in other contexts is prohibited and will throw out a Lua exception."

**Comment by agentzh** [comment]
@hulu1522 I guess you're setting the `jump` argument to a true value? You didn't provide your Lua snippet, so I can only guess here ;)

**Comment by hulu1522** [comment]
@agentzh Your right I was using the `jump` argument with it.  I ended up having to redirect requests in order to clear the URI arguments.  Thanks for helping.  :)

**Comment by agentzh** [comment]
@hulu1522 Well, you could use `ngx.exec` to perform internal redirect in `access_by_lua`, which is much cheaper than 301/302/307 external redirects.

**Comment by hulu1522** [comment]
@agentzh Thanks for the suggestion, unfortunately in this circumstance I need a redirect.  I'm writing my own authentication proxy with SSL and cookie session.  After testing an external redirect was the only one that would work every time.  I'll keep `ngx.exec` in mind as it looks useful in other areas.  I won't have more than 1000 connections at any given time so I'm not too worried.
