### ISSUE TITLE
how to solve the 403 error 

### ISSUE THREAD

**Issue by jiajar** [openresty/ngx_openresty#109]
hi,
When I finished the nginx configuration, I was always getthe  403 error when i visit  /yoga-res,
this is my error log

```
2015/07/04 introduction [error] 3976#0: *62889 directory index of "/home/nginx/app/openresty/nginx/html/" is forbidden.: 100.97.181.249, server: localhost. General: "head / HTTP / 1.0"
```

This is my configuration.
```
server {
    listen 8000;
    server_name localhost ;
    location /yoga-res{
        alias /home/nginx/app/openresty/nginx/html/easyhi;
       autoindex on;
    }
}
```
This is my directory authority.
```
drwxr-xr-x 4 nginx nginx Jul 4 14:24 4096 html
```

**Comment by agentzh** [comment]
@jiajar Seems like your some directories in your path `/home/nginx/app/openresty/nginx/html/` do not have enough permissions (read and execute permissions) for the system account used by your nginx *worker* processes (default to `nobody`).

**Comment by agentzh** [comment]
@jiajar BTW, simply checking the permissions of that `html` directory is not enough. Path resolution of UNIX systems require *all* the containing directories in your path have enough permissions. It's UNIX basics :)

**Comment by jiajar** [comment]
3Q ,this nginx was copyed from the other user,and the `app` directory does not have the execute permissions ! :(
