### ISSUE TITLE
Feature request NAXSI into OpenResty Package

### ISSUE THREAD

**Issue by dtouzeau** [openresty/ngx_openresty#110]
Hi, 
I love your product...
Is it possible to add NAXSI module in OpenResty package ?
http://howtounix.info/howto/naxsi-nginx-firewall

**Comment by agentzh** [comment]
@dtouzeau I believe you can just use the `--add-module=PATH` ./configure option, just with the stock nginx distribution.

**Comment by dtouzeau** [comment]
You are right but it should be added into your "Bundle" way in order to be compiled by default.
What did you think about ?

**Comment by agentzh** [comment]
@dtouzeau Sorry, I'm not feeling comfortable with that because I'm not quite happy with Naxsi's code base. For one thing, it diverges a lot from the standard nginx coding style.

**Comment by agentzh** [comment]
@dtouzeau Also, I have strong opinions on how to implement a highly dynamic and efficient nginx-based WAF (well, you know that I've been working for CloudFlare which comes with an OpenResty-based WAF product). So OpenResty will eventually come with a powerful opensource WAF module in the near future :)

**Comment by dtouzeau** [comment]
Super !!! having a schedule about implementing WAF ??

**Comment by agentzh** [comment]
@dtouzeau All I can say at this point is "as soon as I can manage" :) Hopefully this year :)

**Comment by matth-c3** [comment]
hello @agentzh , 

any news :) ?
