### ISSUE TITLE
New relic support 

### ISSUE THREAD

**Issue by sks** [openresty/ngx_openresty#111]
First of all thank you for open resty, 
We are using open resty mainly because of its lua+ redis +ngnix support , and it works great.

I'm asking for a enhancement here , 

Has anyone played with "new relic" support for nginx , Is there any documentation to have openresty installed with "new relic" agent ?

If so , I would like to know how  you went about it ?

Thank you 
Sabith

**Comment by needcaffeine** [comment]
I'm not sure I understand the intent here. The NewRelic plugin can be installed using the following instructions: http://newrelic.com/plugins/nginx-inc/13 — I'm not sure that this fits within the scope of ngx_openresty.

**Comment by sks** [comment]
Thanks @needcaffeine  

Closing this issue as I'm trying to get some support from nginx folks
