### ISSUE TITLE
Add nginx-push-stream-module and spnego-http-auth-nginx-module

### ISSUE THREAD

**Issue by laurivosandi** [openresty/ngx_openresty#113]
Hi,

please also add following components:

https://github.com/wandenberg/nginx-push-stream-module
https://github.com/stnoonan/spnego-http-auth-nginx-module

**Comment by agentzh** [comment]
@laurivosandi Sorry, I'm not interested in adding them as the default components of the OpenResty bundle. One can always use the `./configure` option `--add-module=PATH` to enable new nginx modules in the OpenResty build, just as with the official nginx distribution.

It's worth mentioning that 3rd-party modules that are not maintained by OpenResty developers may cause instabilities in the OpenResty server which we will not provide (free) technical support. Well, you're warned :)
