### ISSUE TITLE
Mac os 10.10 安装失败，请大神指教，谢谢。

### ISSUE THREAD

**Issue by zhangjiachao** [openresty/ngx_openresty#117]
第一：我的电脑已经安装了原生的nginx ，但没有记动。
第二，我从官方下载了1.9.3的安装包，按照提示./configure，下面是错误日志：

----------------------------------------
checking for C compiler

----------------------------------------
checking for --with-ld-opt="-Wl,-rpath,/usr/local/openresty/luajit/lib"

----------------------------------------
checking for gcc builtin atomic operations

----------------------------------------
checking for C99 variadic macros

----------------------------------------
checking for gcc variadic macros

----------------------------------------
checking for unistd.h

----------------------------------------
checking for inttypes.h

----------------------------------------
checking for limits.h

----------------------------------------
checking for sys/filio.h

----------------------------------------
checking for sys/param.h

----------------------------------------
checking for sys/mount.h

----------------------------------------
checking for sys/statvfs.h

----------------------------------------
checking for crypt.h

objs/autotest.c:3:10: fatal error: 'crypt.h' file not found
#include <crypt.h>
         ^
1 error generated.
----------

#include <sys/param.h>
#include <crypt.h>

int main() {
    return 0;
}

----------
cc -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for kqueue's EVFILT_TIMER

----------------------------------------
checking for Darwin 64-bit kqueue millisecond timeout bug

----------------------------------------
checking for sendfile()

----------------------------------------
checking for atomic(3)

----------------------------------------
checking for poll()

----------------------------------------
checking for /dev/poll

objs/autotest.c:4:10: fatal error: 'sys/devpoll.h' file not found
#include <sys/devpoll.h>
         ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/devpoll.h>

int main() {
    int  n, dp; struct dvpoll  dvp;
                  dp = 0;
                  dvp.dp_fds = NULL;
                  dvp.dp_nfds = 0;
                  dvp.dp_timeout = 0;
                  n = ioctl(dp, DP_POLL, &dvp);
                  if (n == -1) return 1;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for crypt()

----------------------------------------
checking for F_READAHEAD

objs/autotest.c:7:14: error: use of undeclared identifier 'F_READAHEAD'
    fcntl(0, F_READAHEAD, 1);;
             ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>

int main() {
    fcntl(0, F_READAHEAD, 1);;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for posix_fadvise()

objs/autotest.c:7:5: warning: implicit declaration of function 'posix_fadvise' is invalid in C99 [-Wimplicit-function-declaration]
    posix_fadvise(0, 0, 0, POSIX_FADV_SEQUENTIAL);;
    ^
objs/autotest.c:7:28: error: use of undeclared identifier 'POSIX_FADV_SEQUENTIAL'
    posix_fadvise(0, 0, 0, POSIX_FADV_SEQUENTIAL);;
                           ^
1 warning and 1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>

int main() {
    posix_fadvise(0, 0, 0, POSIX_FADV_SEQUENTIAL);;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for O_DIRECT

objs/autotest.c:7:23: error: use of undeclared identifier 'O_DIRECT'
    fcntl(0, F_SETFL, O_DIRECT);;
                      ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>

int main() {
    fcntl(0, F_SETFL, O_DIRECT);;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for F_NOCACHE

----------------------------------------
checking for directio()

objs/autotest.c:8:5: warning: implicit declaration of function 'directio' is invalid in C99 [-Wimplicit-function-declaration]
    directio(0, DIRECTIO_ON);;
    ^
objs/autotest.c:8:17: error: use of undeclared identifier 'DIRECTIO_ON'
    directio(0, DIRECTIO_ON);;
                ^
1 warning and 1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/types.h>
                  #include <sys/fcntl.h>

int main() {
    directio(0, DIRECTIO_ON);;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for statfs()

----------------------------------------
checking for statvfs()

----------------------------------------
checking for dlopen()

----------------------------------------
checking for sched_yield()

----------------------------------------
checking for SO_SETFIB

objs/autotest.c:7:31: error: use of undeclared identifier 'SO_SETFIB'
    setsockopt(0, SOL_SOCKET, SO_SETFIB, NULL, 0);
                              ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>

int main() {
    setsockopt(0, SOL_SOCKET, SO_SETFIB, NULL, 0);
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for SO_REUSEPORT

----------------------------------------
checking for SO_ACCEPTFILTER

objs/autotest.c:7:31: error: use of undeclared identifier 'SO_ACCEPTFILTER'
    setsockopt(0, SOL_SOCKET, SO_ACCEPTFILTER, NULL, 0);
                              ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>

int main() {
    setsockopt(0, SOL_SOCKET, SO_ACCEPTFILTER, NULL, 0);
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for TCP_DEFER_ACCEPT

objs/autotest.c:9:32: error: use of undeclared identifier 'TCP_DEFER_ACCEPT'
    setsockopt(0, IPPROTO_TCP, TCP_DEFER_ACCEPT, NULL, 0);
                               ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
                  #include <netinet/in.h>
                  #include <netinet/tcp.h>

int main() {
    setsockopt(0, IPPROTO_TCP, TCP_DEFER_ACCEPT, NULL, 0);
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for TCP_KEEPIDLE

objs/autotest.c:9:32: error: use of undeclared identifier 'TCP_KEEPIDLE'
    setsockopt(0, IPPROTO_TCP, TCP_KEEPIDLE, NULL, 0);
                               ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
                  #include <netinet/in.h>
                  #include <netinet/tcp.h>

int main() {
    setsockopt(0, IPPROTO_TCP, TCP_KEEPIDLE, NULL, 0);
                  setsockopt(0, IPPROTO_TCP, TCP_KEEPINTVL, NULL, 0);
                  setsockopt(0, IPPROTO_TCP, TCP_KEEPCNT, NULL, 0);
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for TCP_FASTOPEN

objs/autotest.c:9:32: error: use of undeclared identifier 'TCP_FASTOPEN'
    setsockopt(0, IPPROTO_TCP, TCP_FASTOPEN, NULL, 0);
                               ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
                  #include <netinet/in.h>
                  #include <netinet/tcp.h>

int main() {
    setsockopt(0, IPPROTO_TCP, TCP_FASTOPEN, NULL, 0);
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for TCP_INFO

objs/autotest.c:9:24: error: invalid application of 'sizeof' to an incomplete type 'struct tcp_info'
    socklen_t optlen = sizeof(struct tcp_info);
                       ^     ~~~~~~~~~~~~~~~~~
objs/autotest.c:9:38: note: forward declaration of 'struct tcp_info'
    socklen_t optlen = sizeof(struct tcp_info);
                                     ^
objs/autotest.c:10:35: error: variable has incomplete type 'struct tcp_info'
                  struct tcp_info ti;
                                  ^
objs/autotest.c:9:38: note: forward declaration of 'struct tcp_info'
    socklen_t optlen = sizeof(struct tcp_info);
                                     ^
objs/autotest.c:15:46: error: use of undeclared identifier 'TCP_INFO'
                  getsockopt(0, IPPROTO_TCP, TCP_INFO, &ti, &optlen);
                                             ^
3 errors generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
                  #include <netinet/in.h>
                  #include <netinet/tcp.h>

int main() {
    socklen_t optlen = sizeof(struct tcp_info);
                  struct tcp_info ti;
                  ti.tcpi_rtt = 0;
                  ti.tcpi_rttvar = 0;
                  ti.tcpi_snd_cwnd = 0;
                  ti.tcpi_rcv_space = 0;
                  getsockopt(0, IPPROTO_TCP, TCP_INFO, &ti, &optlen);
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for accept4()

objs/autotest.c:7:5: warning: implicit declaration of function 'accept4' is invalid in C99 [-Wimplicit-function-declaration]
    accept4(0, NULL, NULL, SOCK_NONBLOCK);
    ^
objs/autotest.c:7:28: error: use of undeclared identifier 'SOCK_NONBLOCK'
    accept4(0, NULL, NULL, SOCK_NONBLOCK);
                           ^
1 warning and 1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>

int main() {
    accept4(0, NULL, NULL, SOCK_NONBLOCK);
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for eventfd()

objs/autotest.c:4:10: fatal error: 'sys/eventfd.h' file not found
#include <sys/eventfd.h>
         ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/eventfd.h>

int main() {
    (void) eventfd(0, 0);
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for eventfd() (SYS_eventfd)

objs/autotest.c:7:13: error: use of undeclared identifier 'SYS_eventfd'
    int n = SYS_eventfd;
            ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/syscall.h>

int main() {
    int n = SYS_eventfd;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for int size

----------------------------------------
checking for long size

----------------------------------------
checking for long long size

----------------------------------------
checking for void * size

----------------------------------------
checking for uint64_t

----------------------------------------
checking for sig_atomic_t

----------------------------------------
checking for sig_atomic_t size

----------------------------------------
checking for socklen_t

----------------------------------------
checking for in_addr_t

----------------------------------------
checking for in_port_t

----------------------------------------
checking for rlim_t

checking for uintptr_t

checking for system byte ordering

----------------------------------------
checking for size_t size

----------------------------------------
checking for off_t size

----------------------------------------
checking for time_t size

----------------------------------------
checking for setproctitle()

objs/autotest.c:7:5: warning: implicit declaration of function 'setproctitle' is invalid in C99 [-Wimplicit-function-declaration]
    setproctitle("test");;
    ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "_setproctitle", referenced from:
      _main in autotest-a72ff7.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
----------

#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

int main() {
    setproctitle("test");;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for pread()

----------------------------------------
checking for pwrite()

----------------------------------------
checking for sys_nerr

107
----------------------------------------
checking for localtime_r()

----------------------------------------
checking for posix_memalign()

----------------------------------------
checking for memalign()

objs/autotest.c:5:28: fatal error: 'malloc.h' file not found
                  #include <malloc.h>
                           ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
                  #include <malloc.h>

int main() {
    void *p; p = memalign(4096, 4096);
                  if (p == NULL) return 1;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for mmap(MAP_ANON|MAP_SHARED)

----------------------------------------
checking for mmap("/dev/zero", MAP_SHARED)

----------------------------------------
checking for System V shared memory

----------------------------------------
checking for POSIX semaphores

objs/autotest.c:8:23: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
                  if (sem_init(&sem, 1, 0) == -1) return 1;
                      ^
/usr/include/sys/semaphore.h:55:5: note: 'sem_init' has been explicitly marked deprecated here
int sem_init(sem_t *, int, unsigned int) __deprecated;
    ^
objs/autotest.c:9:19: warning: 'sem_destroy' is deprecated [-Wdeprecated-declarations]
                  sem_destroy(&sem);;
                  ^
/usr/include/sys/semaphore.h:53:5: note: 'sem_destroy' has been explicitly marked deprecated here
int sem_destroy(sem_t *) __deprecated;
    ^
2 warnings generated.

----------------------------------------
checking for POSIX semaphores in libpthread

objs/autotest.c:8:23: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
                  if (sem_init(&sem, 1, 0) == -1) return 1;
                      ^
/usr/include/sys/semaphore.h:55:5: note: 'sem_init' has been explicitly marked deprecated here
int sem_init(sem_t *, int, unsigned int) __deprecated;
    ^
objs/autotest.c:9:19: warning: 'sem_destroy' is deprecated [-Wdeprecated-declarations]
                  sem_destroy(&sem);;
                  ^
/usr/include/sys/semaphore.h:53:5: note: 'sem_destroy' has been explicitly marked deprecated here
int sem_destroy(sem_t *) __deprecated;
    ^
2 warnings generated.

----------------------------------------
checking for POSIX semaphores in librt

objs/autotest.c:8:23: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
                  if (sem_init(&sem, 1, 0) == -1) return 1;
                      ^
/usr/include/sys/semaphore.h:55:5: note: 'sem_init' has been explicitly marked deprecated here
int sem_init(sem_t *, int, unsigned int) __deprecated;
    ^
objs/autotest.c:9:19: warning: 'sem_destroy' is deprecated [-Wdeprecated-declarations]
                  sem_destroy(&sem);;
                  ^
/usr/include/sys/semaphore.h:53:5: note: 'sem_destroy' has been explicitly marked deprecated here
int sem_destroy(sem_t *) __deprecated;
    ^
2 warnings generated.
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
----------

#include <sys/types.h>
#include <unistd.h>
#include <semaphore.h>

int main() {
    sem_t  sem;
                  if (sem_init(&sem, 1, 0) == -1) return 1;
                  sem_destroy(&sem);;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib -lrt
----------

----------------------------------------
checking for struct msghdr.msg_control

----------------------------------------
checking for ioctl(FIONBIO)

----------------------------------------
checking for struct tm.tm_gmtoff

----------------------------------------
checking for struct dirent.d_namlen

----------------------------------------
checking for struct dirent.d_type

----------------------------------------
checking for sysconf(_SC_NPROCESSORS_ONLN)

----------------------------------------
checking for openat(), fstatat()

----------------------------------------
checking for getaddrinfo()

----------------------------------------
checking for LuaJIT library in /Users/Jochen/Desktop/ngx_openresty-1.9.3.1/build/luajit-root/usr/local/openresty/luajit/lib and /Users/Jochen/Desktop/ngx_openresty-1.9.3.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 (specified by the LUAJIT_LIB and LUAJIT_INC env, with -ldl)

----------------------------------------
checking for export symbols by default (-E)

ld: unknown option: -E
clang: error: linker command failed with exit code 1 (use -v to see invocation)
----------

#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>

int main() {
    printf("hello");;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-E
----------

----------------------------------------
checking for export symbols by default (--export-all-symbols)

ld: unknown option: --export-all-symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
----------

#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>

int main() {
    printf("hello");;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,--export-all-symbols
----------

----------------------------------------
checking for SO_PASSCRED

objs/autotest.c:8:31: error: use of undeclared identifier 'SO_PASSCRED'
    setsockopt(1, SOL_SOCKET, SO_PASSCRED, NULL, 0);;
                              ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>

int main() {
    setsockopt(1, SOL_SOCKET, SO_PASSCRED, NULL, 0);;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib
----------

----------------------------------------
checking for PCRE library

----------------------------------------
checking for PCRE JIT support

Undefined symbols for architecture x86_64:
  "_pcre_free_study", referenced from:
      _main in autotest-229b13.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
----------

#include <sys/types.h>
#include <unistd.h>
#include <pcre.h>

int main() {
    int jit = 0;
                              pcre_free_study(NULL);
                              pcre_config(PCRE_CONFIG_JIT, &jit);
                              if (jit != 1) return 1;;
    return 0;
}

----------
cc -pipe -O2 -o objs/autotest objs/autotest.c -Wl,-rpath,/usr/local/openresty/luajit/lib -lpcre
----------

----------------------------------------
checking for OpenSSL library

objs/autotest.c:7:5: warning: 'SSL_library_init' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
    SSL_library_init();
    ^
/usr/include/openssl/ssl.h:1569:5: note: 'SSL_library_init' has been explicitly marked deprecated here
int SSL_library_init(void ) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
1 warning generated.

----------------------------------------
checking for zlib library

**Comment by agentzh** [comment]
@zhangjiachao Please, no Chinese here. This place is considered English only. If you really want to use Chinese, please use the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community for more details.

In addition, please do not paste overwhelming text in the ticket. Better use a 3rd-party paste services like gist.github.com and just shares the link here. It can make this place look less messy.

For the installation instructions of OpenResty on Mac OS X, please check out this page for details:

https://openresty.org/#Installation

This looks apparently due to

1. you're not using the latest OpenResty bundle release, and/or
2. you're not specifying the PCRE library and include paths correctly on the `./configure` command line.

**Comment by jgonggrijp** [comment]
I appear to have the same issue, with OpenResty version 1.9.3.1 on OS X 10.10.5. I ran

    ./configure --with-pcre-jit --with-ipv6 --with-cc-opt="-I/opt/local/include -I/usr/local/include" --with-ld-opt="-L/opt/local/lib -L/usr/local/lib" --with-http_postgres_module

and got

    ./configure: error: ngx_http_lua_module requires the Lua or LuaJIT library and LUAJIT_LIB is defined as /Volumes/scratch/ngx_openresty-1.9.3.1/build/luajit-root/usr/local/openresty/luajit/lib and LUAJIT_INC (path for lua.h) /Volumes/scratch/ngx_openresty-1.9.3.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1, but we cannot find LuaJIT there.

The errors in `build/nginx-1.9.3/objs/autoconf.err` are

    checking for crypt.h
    
    objs/autotest.c:3:10: fatal error: 'crypt.h' file not found
    #include <crypt.h>
             ^
    1 error generated.

    ----

    checking for /dev/poll
    
    objs/autotest.c:4:10: fatal error: 'sys/devpoll.h' file not found
    #include <sys/devpoll.h>
             ^
    1 error generated.

    ----

    checking for F_READAHEAD
    
    objs/autotest.c:7:14: error: use of undeclared identifier 'F_READAHEAD'
        fcntl(0, F_READAHEAD, 1);;
                 ^
    1 error generated.

    ----

    checking for posix_fadvise()
    
    objs/autotest.c:7:5: warning: implicit declaration of function 'posix_fadvise' is invalid in C99 [-Wimplicit-function-declaration]
        posix_fadvise(0, 0, 0, POSIX_FADV_SEQUENTIAL);;
        ^
    objs/autotest.c:7:28: error: use of undeclared identifier 'POSIX_FADV_SEQUENTIAL'
        posix_fadvise(0, 0, 0, POSIX_FADV_SEQUENTIAL);;
                               ^
    1 warning and 1 error generated.

Similar for `O_DIRECT` (7:23), `directio()` (8:5, 8:17), `SO_SETFIB` (7:31), `SO_ACCEPTFILTER` (7:31), `TCP_DEFER_ACCEPT` (9:32), `TCP_KEEPIDLE` (9:32) and several more.

Please let me know if I can help in any way.

**Comment by agentzh** [comment]
@jgonggrijp Please paste *all* the console output of your `./configure` command as well as the *full* content of `autoconf.err` file. Please use web paste services like gist.github.com and just share the link here.

Just FYI, I'm also running Mac OS X 10.10.5 locally and I didn't see such issues while testing ngx_openresty 1.9.3.1.

**Comment by jgonggrijp** [comment]
Here you go. https://gist.github.com/jgonggrijp/f90feab8247687cf105d

**Comment by agentzh** [comment]
@jgonggrijp Okay, I see that you have an incompatible version of Lua headers under your `/opt/local/include/` or `/usr/local/include/`, as evidenced by the following snippet in your `autoconf.err`:

```
objs/autotest.c:8:5: error: unsupported Lua language version
#   error unsupported Lua language version
    ^
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <lauxlib.h>

int main() {
#if LUA_VERSION_NUM != 501
#   error unsupported Lua language version
#endif
(void) luaL_newstate();;
    return 0;
}
```

Please remove that offending Lua before the build.

**Comment by agentzh** [comment]
@jgonggrijp Okay, I've committed a patch to ngx_lua's master so that we can always choose the bundled version of the LuaJIT in OpenResty regardless what versions of Lua are installed under the paths specified in the `--with-cc-opt` and `--with-ld-opt` options of `./configure`.

Will you please try the following OpenResty tarball on your side?

https://openresty.org/download/ngx_openresty-1.9.3.2rc0.tar.gz

You no longer need to clean up incompatible versions of Lua in your system with this tarball. Let me know if it works for you. Thanks!

**Comment by jgonggrijp** [comment]
Great, I felt reluctant about removing my LuaJIT 2.0.4 install under /usr/local and now I probably don't need to do that anymore! Will try the new tarball later today (in about 9 hours).

**Comment by agentzh** [comment]
@jgonggrijp Cool, thanks.

**Comment by agentzh** [comment]
@jgonggrijp But I'm pretty sure it was not your LuaJIT 2.0.4 under /usr/local since it's compatible with Lua 5.1.

**Comment by jgonggrijp** [comment]
Ah right, I also have Lua 5.3.1 installed under `/opt/local`, but I wasn't aware of it because it was installed as a dependency of some of my ports. Uninstalling that would have been a real hassle!

**Comment by agentzh** [comment]
@jgonggrijp Fair enough.

Please let me know if the new openresty tarball give above fixes the issue without hassles on your side :)

**Comment by jgonggrijp** [comment]
Issue solved without hassle, thanks a lot!

**Comment by agentzh** [comment]
@jgonggrijp Glad to hear that. Thanks for your feedback.

**Comment by agentzh** [comment]
@zhangjiachao Any progress have you made on your side? You don't seem to have the same issue as @jgonggrijp though (according to your autoconf.err file contents).

**Comment by agentzh** [comment]
Consider it resolved.
