### ISSUE TITLE
连接mongodb3.0权限认证

### ISSUE THREAD

**Issue by RicherdLee** [openresty/ngx_openresty#118]
我在使用openresty连接mongo时，遇到了权限认证问题，github上的项目都未涉及到mongodb3.0权限认证问题。
请问你们是如何实现的

**Comment by agentzh** [comment]
@RicherdLee Please don't use Chinese here. This place is supposed to be English only. If you really want to use Chinese, please join the openresty (Chinese) mailing list and post there instead. Please see https://openresty.org/#Community Thank you for your cooperation.

Regarding your question, the official OpenResty does not provide any MongoDB libraries, so you should rely on community implementations instead. This means this question is also a bit off-topic for this ngx_openresty project (well, it's not OT if you are asking for a MongoDB library in the official OpenResty bundle). Just my 2 cents.
