### ISSUE TITLE
Openresty get ssl certificate

### ISSUE THREAD

**Issue by rbnacharya** [openresty/ngx_openresty#119]
I want to view client certificate when there is ssl request made, is that possible in openresty?

**Comment by dol** [comment]
You can access all the SSL [Embedded Variables](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables) like the following:
`local client_cert = ngx.var.ssl_client_cert`
The best way to ask questions about the openresty project is the mailing list => https://groups.google.com/forum/#!forum/openresty-en

**Comment by rbnacharya** [comment]
Thanks, that worked!!
