### ISSUE TITLE
require other lua file failed

### ISSUE THREAD

**Issue by dragon9783** [openresty/ngx_openresty#120]
### [Environment]
openresty 1.9.3.1
ubuntu 14.04
### [Directory] 
.
├── client_body_temp
├── conf
│   └── nginx.conf
├── fastcgi_temp
├── logs
│   ├── access.log
│   ├── error.log
│   └── nginx.pid
├── lua
│   ├── comm
│   │   └── mysqlLib.lua
│   ├── dbMysql.lua
│   ├── test_hello.lua
│   └── test_mysql.lua
├── proxy_temp
├── scgi_temp
└── uwsgi_temp

#### test_mysql.lua    
`local mysql = require("comm.mysqlLib")`
#### comm/mysqlLib.lua
`local _M = { _VERSION = '0.01' }`
`local mysql = require("resty.mysql")`
`function _M.getClient() `  
`end`
`function _M.close()`
`end`
`return _M`    
### Issure
`lua entry thread aborted: runtime error: /labrory/openresty/lua/test_mysql.lua:3: module 'comm.mysqlLib' not found`

and i add comm directory to package.path, but it doesn't work, anyone help me?

**Comment by dragon9783** [comment]
### Error Log
2015/10/08 17:22:45 [error] 30813#0: *58 lua entry thread aborted: runtime error: /labrory/openresty/lua/test_mysql.lua:3: module 'comm.mysqlLib' not found:
	no field package.preload['comm.mysqlLib']
	no file '/usr/local/openresty/lualib/comm/mysqlLib.lua'
	no file '/usr/local/openresty/lualib/comm/mysqlLib/init.lua'
	no file './comm/mysqlLib.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-alpha/comm/mysqlLib.lua'
	no file '/usr/local/share/lua/5.1/comm/mysqlLib.lua'
	no file '/usr/local/share/lua/5.1/comm/mysqlLib/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/comm/mysqlLib.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/comm/mysqlLib/init.lua'
	no file '/usr/local/openresty/lualib/comm/mysqlLib.so'
	no file './comm/mysqlLib.so'
	no file '/usr/local/lib/lua/5.1/comm/mysqlLib.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/comm/mysqlLib.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/lualib/comm.so'
	no file './comm.so'
	no file '/usr/local/lib/lua/5.1/comm.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/comm.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/labrory/openresty/lua/test_mysql.lua:3: in function </labrory/openresty/lua/test_mysql.lua:1>, client: 127.0.0.1, server: , request: "GET /test_mysql

**Comment by agentzh** [comment]
@dragon9783 The Lua VM should list all the paths it ever attempted after the `module ... not found` line in that very error message. You can check that path list for debugging.

Basically, you should use the `-p PATH` option to start your nginx and `PATH` points to the root of your application directory tree. And then configure

```nginx
lua_package_path '$prefix/lua/?.lua;;';
```

literally in your `nginx.conf` according to your application tree structure given above. Oh, please note that both the `$prefix` variable and the question mark (`?`) have special meanings to the Lua VM, so do not substitute it by hand with anything else.

**Comment by agentzh** [comment]
@dragon9783 Also, if Lua VM complains that a existent file path as "no file", it actually means the system account used for your nginx worker processes (it is the `nobody` account by default) do not have enough permissions to resolve that path or access that file.

**Comment by dragon9783** [comment]
@agentzh Sudoer for my nginx worker processes and in lua file i add  package.path, it doesn't work , so must add it in nginx conf?

**Comment by dragon9783** [comment]
@agentzh ok, i add full path in package.path, it's work, thanks alot!

**Comment by agentzh** [comment]
@dragon9783 You shouldn't hard-code an absolute path in module search path list. That's a bad practice. Also, appending stuff to `package.path` in the request handler can result in a memory leak.

You should only specify the root of your application tree via the `-p` option while starting nginx. See

http://openresty.org/#GettingStarted

How come my `lua_package_path` configuration does not work for you? Have you specify the `-p` option properly? Keep an eye on the paths attempted by the Lua VM in your error.log file.

**Comment by agentzh** [comment]
@dragon9783 In general, modifying `package.path` is not recommended. Use `lua_package_path` (and `lua_package_cpath` if DSO is involved) in your `nginx.conf` and start your nginx with `-p PATH` option instead.

**Comment by agentzh** [comment]
@dragon9783 BTW, the PATH specified in the `-p` option of the nginx command line is the value of the special `$prefix` variable in my configuration snippet for `lua_package_path`.

**Comment by dragon9783** [comment]
ok, i already try it, and work well, thanks alot
