### ISSUE TITLE
How to create Openresty Global variable

### ISSUE THREAD

**Issue by RicherdLee** [openresty/ngx_openresty#121]
I want to create a global variable, and when the openresty first starts, the framework core file will be loaded only once.
I tried ngx.ctx,but ervery access,the ngx.ctx is nil.
Can give me a suggestion。 Thanks

**Comment by agentzh** [comment]
@RicherdLee You can just use the `init_by_lua` directive for it:

https://github.com/openresty/lua-nginx-module/#init_by_lua

It runs before nginx forks off worker processes.

**Comment by agentzh** [comment]
@RicherdLee BTW, such general questions should go to the openresty-en mailing list instead. Please see

https://openresty.org/#Community

Thanks for your cooperation :)

**Comment by RicherdLee** [comment]
Thanks for your help.
 I will go to the mailing list instead next time.

**Comment by agentzh** [comment]
@RicherdLee Oh, BTW, use of Lua global variables is discouraged. You should really use custom Lua modules (`.lua` files) instead. Please see

https://github.com/openresty/lua-nginx-module#lua-variable-scope

**Comment by RicherdLee** [comment]
Through Variable Scope Lua, I think I should change my mind and abandon the idea of a global variable.
By setting lua_code_cache to cache, and use the DrizzleNginxModule to opration database.
Thank you for pointing out the fundamental problem.
