### ISSUE TITLE
OpenBSD support?

### ISSUE THREAD

**Issue by w00000000000000000000000** [openresty/ngx_openresty#124]
Update: ngx_openresty compiled successfully on OpenBSD 5.8

**Comment by agentzh** [comment]
@w00000000000000000000000 Let me know if you have any particular issues on that system.

**Comment by w00000000000000000000000** [comment]
Thank you, I intend to use PHP-FPM and LUA modules necessary?

**Comment by agentzh** [comment]
@w00000000000000000000000 Sorry, I cannot parse your English sentence above.

**Comment by w00000000000000000000000** [comment]
1.9.3.1 release possible with configure --without-any-lua ?

**Comment by agentzh** [comment]
@w00000000000000000000000 Please do not abuse this ticket system for instant messaging. How does your last question have anything to do with the title of this ticket?

**Comment by agentzh** [comment]
@w00000000000000000000000 General discussions should go to the openresty mailing lists. Please see https://openresty.org/#Community But again, ask your questions seriously and responsibly.

**Comment by w00000000000000000000000** [comment]
Thank you for noticed.
