### ISSUE TITLE
SetMatchMode is DEPRECATED

### ISSUE THREAD

**Issue by crealist** [openresty/ngx_openresty#125]
Сфинкс забивает лог этим:
[Sphinx::Search][886] SetMatchMode is DEPRECATED. Do not call this method - use extended query syntax instead. at /usr/local/share/perl/5.20.2/Sphinx/Search.pm line 886.

А у нас в поиске от Энди SetMatchMode очень много где. Нужно бы переделать.

**Comment by agentzh** [comment]
@crealist This place is considered English only. And I cannot read Russian. Sorry. Furthermore, I don't think your question is related to the current project (ngx_openresty).
