### ISSUE TITLE
Unspecified build dependency:  Markdown::Pod

### ISSUE THREAD

**Issue by mcd-php** [openresty/ngx_openresty#126]
The first make fails, needed to `sudo cpanm Markdown::Pod`. Code installing in some local temp dir ?

**Comment by agentzh** [comment]
@mcd-php Maybe just add the line "cpan Markdown::Pod" in the README?

**Comment by rinrinne** [comment]
+ dos2unix package on Ubuntu14.04

**Comment by agentzh** [comment]
Fixed the missing build dependencies in the docs. Thanks.
