### ISSUE TITLE
nginx will be unresponsive for a very long time after write several lines in lua code

### ISSUE THREAD

**Issue by Dyluck** [openresty/ngx_openresty#129]
* code example:

>    location = /test {
>		content_by_lua '
>    			for i=0,1000000,1 do
>				ngx.say(i)
>			end
>			';
>	}

* and then execute cmd:

>    curl localhost/test

* finally, curl get incomplete content and blocked , one nginx process will be unresponsive for a very very long time.

**Comment by agentzh** [comment]
@Dyluck Don't do that. `ngx.say` is expensive because it always invokes the whole nginx output filter chain (and often a syscall as well). You should buffer such little bits yourself with a Lua table instead.

**Comment by Dyluck** [comment]
@agentzh got it, thanks!
