### ISSUE TITLE
nginx可不可以在location里先返回一个请求，但是可以继续后续处理其他的逻辑

### ISSUE THREAD

**Issue by adpoint** [openresty/ngx_openresty#134]
请问一下春哥，一个请求发到nginx，比如curl请求，可不可以在location里先返回这个请求，还能继续处理其他逻辑，就相当于使用curl给nginx发一个通知，nginx收到这个通知之后能够处理自己的逻辑，而不会阻塞这个请求？

**Comment by lancelijade** [comment]
ngx.timer.at()

Lance

2015-12-12 12:18 GMT+08:00 adpoint <notifications@github.com>:

**Comment by lancelijade** [comment]
ngx.eof()



Lance

2015-12-12 17:26 GMT+08:00 Lance <lancelijade@gmail.com>:

**Comment by adpoint** [comment]
@lancelijade  thanks very much!

**Comment by agentzh** [comment]
@adpoint Please do not use Chinese here. Thank you. BTW, such general questions should go to the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community for more details. Thanks for your cooperation.
