### ISSUE TITLE
openresty可以代理一个请求，同时发送到后台多个服务器吗

### ISSUE THREAD

**Issue by sdcuike** [openresty/ngx_openresty#135]
同主题。

**Comment by doujiang24** [comment]
@sdcuike  Please, no Chinese here. This place is considered English only. If you really want to use Chinese. Please join the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community

Regarding your question, you can use ngx.thread.spawm + lua-resty-http(recommended) or ngx.location.capture_multi + proxy_pass
https://github.com/openresty/lua-nginx-module/#ngxthreadspawn
https://github.com/openresty/lua-nginx-module/#ngxlocationcapture_multi

**Comment by sdcuike** [comment]
thank you
