### ISSUE TITLE
openresty 是否可以支持  stream_core_module

### ISSUE THREAD

**Issue by wentianle** [openresty/ngx_openresty#137]
openresty 是否可以支持  stream_core_module 这样就可以更好用来做 tcp proxy 了

**Comment by doujiang24** [comment]
@wentianle May be you need ngx_stream_lua_module, it's on the road.

Please do not use Chinese here. Thank you. BTW, such general questions should go to the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community for more details. Thanks for your cooperation.
