### ISSUE TITLE
能否支持动态调整Host匹配Server的功能

### ISSUE THREAD

**Issue by xiuluo999** [openresty/ngx_openresty#138]
我们的项目中使用302调度方式，最终调度返回的Location类似 http://{ip}/{domain}/{uri}，这样就有一个问题，请求无法进入到domain对应的Server配置中去，我们试过在比较靠前的parser(init_worker)中设置请求的host，但是仍然无法工作，最后研究了源代码发现这些阶段处于配置解析之后，最终无奈只能修改nginx源代码实现我们的功能。这种场景在直播下载应用中很普遍，如果openresty能处理就方便多了。

**Comment by agentzh** [comment]
@xiuluo999 Please, do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community Thanks for your cooperation.

Regarding your question, we usually use a single `server {}` block in `nginx.conf` while use Lua to dynamically load, cache, and switch different virtual server related configurations in that single `server {}` block. For example, CloudFlare uses a single `server {}` block to serve millions of different zones (or origin sites) using this approach.

**Comment by kalons** [comment]
sorry for using Chinese here , Im xiuluo999, this is my another account,  thanks for ur reply. u mean make a server{} block as default server and then switch different server logic by lua, or even just do a local proxy pass to real virtual server

**Comment by agentzh** [comment]
@kalons I meant the former, all in the same server, no extra proxying needed. Dynamic configurations and dynamic CDN. I cannot afford running millions of "real virtual servers" either.
