### ISSUE TITLE
MacOS 编译找不到 ngx_shared_config.h

### ISSUE THREAD

**Issue by EtherDream** [openresty/ngx_openresty#140]
/usr/local/include/ngx_auto_config.h:420:9: fatal error: 'ngx_shared_config.h' file not found

**Comment by agentzh** [comment]
@EtherDream Are you following the steps for Mac OS X on the following page?

https://openresty.org/#Installation

**Comment by EtherDream** [comment]
加了 --with-openssl=path 就出问题了

**Comment by agentzh** [comment]
@EtherDream Please, no Chinese here. Thank you.

Regarding your question, `--with-openssl=PATH` requires the *source tree* of OpenSSL instead of the installation tree.

**Comment by EtherDream** [comment]
cd ngx_openresty-VERSION/

wget https://www.openssl.org/source/openssl-1.0.2e.tar.gz
tar xvf openssl-1.0.2e.tar.gz

./configure --with-openssl=./openssl-1.0.2e

make

......

In file included from src/core/nginx.c:8:
In file included from src/core/ngx_config.h:34:
In file included from src/os/unix/ngx_darwin_config.h:57:
/usr/local/include/ngx_auto_config.h:420:9: fatal error: 'ngx_shared_config.h' file not found
#include<ngx_shared_config.h>
        ^
1 error generated.

**Comment by agentzh** [comment]
@EtherDream Seems like your system environment is messed up. Do you know where this `/usr/local/include/ngx_auto_config.h` file comes from? It looks like a historical bad NGINX installation by incorrectly copying nginx header files to the system include paths. Try removing it if it is not intentional.

**Comment by EtherDream** [comment]
solved. thanks very much!
