### ISSUE TITLE
OpenResty windows cannot even serve as a simple HTTP file server within LAN

### ISSUE THREAD

**Issue by chenzx** [openresty/ngx_openresty#142]
I have tried OpenResty for a simple HTTP file server on Windows 10(use its windows prebuilt edition), my  conf:

    server {
        listen 8000; #I‘ve installed XAMPP as my local MediaWiki/Wordpress server;
        server_name  chenzx  alias  chenzx.localhost;
        location / {
            root   /f:/;
            index  index.html index.htm;
            autoindex on;
        }
    }

But when access from browser, i got a 403. Error log:

2016/01/10 18:01:00 [error] 35808#25224: *13 directory index of "f:/" is forbidden, client: 127.0.0.1, server: chenzx, request: "GET / HTTP/1.1", host: "127.0.0.1:8000"

**Comment by kindy** [comment]
I guess on windows, you should use path like "f:/", without prefix "/".
like in [this post](http://stackoverflow.com/questions/22870814/nginx-mapped-hard-drive-network-sharing).

it's about Nginx, but not OpenResty.

**Comment by chenzx** [comment]
no no no, f:/ is also no-use.

I know there may be a problem with Nginx, but i hope better to fix it in
OpenResty. Since OpenResty fixes a lot patch to Nginx?

Your saying "it's about Nginx, but not OpenResty" is not responsible.

2016-01-10 18:18 GMT+08:00 Kindy Lin <notifications@github.com>:

**Comment by agentzh** [comment]
@chenzx Are you 100% sure you have an index.html page under F:/? Because from the error message, you don't have a file named index.html or index.htm.

**Comment by chenzx** [comment]
Yes, of couse, i have no index file.

But i set autoindex on; according to some web tutorials.

**Comment by chenzx** [comment]
I want to test whether Nginx supports HTTP Range requests under windows, since i want to make OpenResty/Nginx a simple HTTP Video streaming server....

**Comment by agentzh** [comment]
@chenzx Then it seems that you are having a permission issue. Maybe you should try some places other than the root partition of your windows file system?

**Comment by agentzh** [comment]
@chenzx I tried with a local partition C:\ and it works as expected on my 64-bit Windows 10 system:

```nginx
location / {
    root c:/;
    index  index.html index.htm;
    autoindex on;
}            
```

```console
$ curl localhost/
<html>
<head><title>Index of /</title></head>
<body bgcolor="white">
<h1>Index of /</h1><hr><pre><a href="../">../</a>
<a href="%24Recycle.Bin/">$Recycle.Bin/</a>                                      27-Oct-2015 10:36                   -
<a href="%24WINDOWS.~BT/">$WINDOWS.~BT/</a>                                      01-Dec-2015 05:09                   -
<a href="Config.Msi/">Config.Msi/</a>                                        13-Jan-2016 07:10                   -
<a href="Documents%20and%20Settings/">Documents and Settings/</a>                            10-Jul-2015 12:21                   -
<a href="MinGW/">MinGW/</a>                                             28-Oct-2015 02:45                   -
<a href="PerfLogs/">PerfLogs/</a>                                          10-Jul-2015 11:04                   -
<a href="Program%20Files/">Program Files/</a>                                     13-Jan-2016 07:09                   -
...
```

**Comment by chenzx** [comment]
Oh, you are right, maybe Windows has some strict pemission problems with ROOT drive path...

But i also hesitate there is short of some flexibility with Nginx/Windows port...

**Comment by agentzh** [comment]
@chenzx Maybe it's just your Windows's security settings. It works fine with root partitions like C:/ on my side.

**Comment by chenzx** [comment]
I'll try tomorrow at my working office.

Since your env is working right, there should be some problem that really matters.

**Comment by chenzx** [comment]
@agentzh Hi, 你说的我明天试一下看看。看过你之前的一篇访谈，说是在Ali做过一段时间的基于WebKit／Firefox的智能爬虫研究（基于可视化特性），有兴趣具体说一下吗？

我现在正考虑做一个基于Chromium内核的客户端智能爬虫。mail：chenzx6 AT lenovo.com

**Comment by chenzx** [comment]
@agentzh I retried today, use c:/ & f:/，both ok.

Cannot figure out why it failed days before when i first used OpenResty.

Also, i noticed OpenResty/Windows cannot autoindex chinese-encoded filenames to display correctly. Chrome default uses utf-8 encoding, but OpenResty/Windows's default output encoding is GBK.

**Comment by agentzh** [comment]
@chenzx Well, this one is easy. Just add the following line to your `location {}` block:

```
charset gbk;
```

Just tested on my Windows 10 and the Chinese directory names are displayed okay in Google Chrome.

**Comment by chenzx** [comment]
@agentzh 无论我使用charset gbk; 还是charset utf-8; 中文目录/文件名可以正常显示，但是无法进一步点击/点进去查看。Nginx的autoindex模块似乎对中文文件路径的支持还是有点问题。

**Comment by chenzx** [comment]
I have tested using Video.js library, seems Nginx/OpenResty supports HTTP Range requests.

But the annoying problem is it doesn't support Chinese-encoded filenames(for real downloading).

Days before i modified Python's builtin SimpleHTTPServer.py to implement this, but it's too ugly coded.

**Comment by agentzh** [comment]
@chenzx Please, no Chinese here. This place is considered English only. If you really want to use Chinese, please join the opernesty (Chinese) mailing list instead. Please see https://openresty.org/#Community Thanks for your cooperation.

Regarding your question, yes, it seems that the autoindex module of NGINX indeed cannot deal with non-ASCII character file entries on Windows:

https://forum.nginx.org/read.php?21,234255,234264#msg-234264

Windows is indeed complicated in the multi-byte character set handling, it seems.

It should work fine on Linux though :)

**Comment by agentzh** [comment]
@chenzx Better avoid non-ASCII characters in the file names and directory names in the first place when you are directly mapping them to the outside world.

**Comment by chenzx** [comment]
@chenzx I download video files using XunLei which default contains chinese characters, and i only serve http video streaming in LAN, no outside public networks.

Sorry bother your time, i find another config sample from http://wangheng.org/nginx-set-directory-browsing-and-solve-the-problem-of-chinese-garbled.html：

            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
            charset utf-8,gbk;

But it still doesn't work.

**Comment by lushibi** [comment]
same problem as @chenzx , any chance to resolve or fix that?
@agentzh

**Comment by agentzh** [comment]
@lushibi I think it's not specific to OpenResty, but a limitation in nginx's official module. If you can also reproduce it with the standard nginx win32 binary, then you should really report it to the official nginx mailing list (or the nginx bug tracker system).

**Comment by lushibi** [comment]
ok, got it
