### ISSUE TITLE
openresty template can not be render  page content

### ISSUE THREAD

**Issue by sosojustdo** [openresty/ngx_openresty#143]
最近在学习openresty的模板，结合网上的例子：http://jinnianshilongnian.iteye.com/blog/2187775
在配置简单的hello world模板的时候，结果发现模板不渲染，每次页面输出的是html模板名称，而内容不做加载，请问大家有么有遇到类似的问题？

openresty template can not be render  page content, just print template name, why?

**Comment by agentzh** [comment]
@sosojustdo No Chinese here, please. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community

Regarding your question, lua-resty-template is not an official component of OpenResty, but rather a 3rd-party component. So the best place to report issues in that library is to create an issue here:

https://github.com/bungle/lua-resty-template/issues

BTW, you may want to try out the lemplate compiler here as well:

https://github.com/openresty/lemplate

**Comment by bungle** [comment]
I have already answered that on lua-resty-template, so this can be closed.

**Comment by sosojustdo** [comment]
replace template.lua file, that ok!
 thank you @bungle ,@agentzh
