### ISSUE TITLE
 runtime error: error loading module 'cjson'

### ISSUE THREAD

**Issue by wind930** [openresty/ngx_openresty#64]
hi @agentzh   I recently I began to try to use ngx_openresty when loading the cjson Lua module error, information is as follows:
2014/09/07 10:09:18 [error] 6104#0: *1 lua entry thread aborted: runtime error: error loading module 'cjson' from file '/usr/local/openresty/lualib/cjson.so':
	/usr/local/openresty/lualib/cjson.so:1: unexpected symbol near 'char(127)'
stack traceback:
coroutine 0:
	[C]: ?
	[C]: in function 'require'
	content_by_lua:3: in function <content_by_lua:1>, client: 192.168.0.101

nginx 配置如下：

lua_package_path "/usr/local/openresty/lualib/?.so;/usr/local/openresty/lualib/rds/?.so;/usr/local/openresty/lualib/redis/?.so;/usr/local/openresty/lualib/resty/?.lua;;";

    location /test {
    
	    content_by_lua '	
	    	    
        local cjson = require "cjson"
        
        local colorTable = { 
          sky = "blue", 
          grass = "green", 
          water = "blue", 
          lava = "red" 
        } 

        ngx.say(cjson.encode(colorTable))
		
		';
    }

In compiling and installing ngx_openresty reports no errors, load other Lua or so module are not wrong, only in the cjson module times wrong, wonder not only its reason, do not know what is wrong with.

  Ask, how can I solve, thanks!

**Comment by mohsininayatkhan** [comment]
Hello @agentzh, I am new to linux and nginx.
I have built the nigix with 'lua-nginx-module' and it's displaying following error in niginx error logs

2015/11/10 12:52:26 [error] 30735#0: *17 lua entry thread aborted: runtime error: /opt/ranger/content.lua:3: module 'cjson' not found:
	no field package.preload['cjson']
	no file '/opt/ranger/external/lua-resty-http/lib/cjson.lua'
	no file '/opt/ranger/external/nginx_log_by_lua/cjson.lua'
	no file '/opt/ranger/external/bitset/lib/cjson.lua'
	no file './cjson.lua'
	no file '/usr/local/share/luajit-2.0.2/cjson.lua'
	no file '/usr/local/share/lua/5.1/cjson.lua'
	no file '/usr/local/share/lua/5.1/cjson/init.lua'
	no file './cjson.so'
	no file '/usr/local/lib/lua/5.1/cjson.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/opt/ranger/content.lua:3: in function </opt/ranger/content.lua:1>

**Comment by agentzh** [comment]
@mohsininayatkhan The lua-cjson library is not part of lua-nginx-module. To avoid such troubles, you're recommended to use the OpenResty bundle instead. Please see

https://openresty.org/#Download

**Comment by mohsininayatkhan** [comment]
@agentzh is there any work around because I have applied the following patches on lua-nginx-module.

https://github.com/openresty/lua-nginx-module/pull/590

https://github.com/openresty/lua-nginx-module/pull/519

**Comment by agentzh** [comment]
@mohsininayatkhan You can apply those patches directly to the OpenResty bundle too. Just find the ngx_lua source tree under the `bundle/` directory.

**Comment by mohsininayatkhan** [comment]
Ok, Many thanks for the quick reply :)

**Comment by Shawkaine** [comment]
@agentzh but I still got the same error as @mohsininayatkhan when I tried to require cjson in Lua, how's that I wonder.

**Comment by agentzh** [comment]
@Shawkaine You need to provide enough details like how you setup openresty and the exact error log messages and your nginx.conf configuration. Otherwise we cannot really help.

**Comment by Shawkaine** [comment]
I found out that my Lua version is 5.3. I guess that should be one of the reasons that caused the error.

**Comment by agentzh** [comment]
@Shawkaine Right. Lua 5.3 has an incompatible ABI than the Lua 5.1 ABI used by OpenResty's LuaJIT. You should always use OpenResty's LuaJIT's header files to compile your Lua C modules.

BTW, OpenResty ships with its own lua-cjson by default. Better avoid using your own to prevent any compatibility problems. It should work out of the box.

**Comment by jobs-git** [comment]
despite this, lua-cjson is not working, I got the latest installer for centos from the site.

**Comment by agentzh** [comment]
@jobs-git Please do not hijack unrelated issues.
