### ISSUE TITLE
ngx_lua 0.9.11+ required

### ISSUE THREAD

**Issue by lenxeon** [openresty/ngx_openresty#70]
i used ngx_openresty-1.7.4.1.tar.gz
when use 'local mysql = require "resty.mysql"' in lua
erro ngx_lua 0.9.11+ required

**Comment by diyism** [comment]
Why does lua-resty-mysql need ngx_lua 0.9.11? I test it on ngx_lua 0.9.5 with version checking commented, and it works well

**Comment by agentzh** [comment]
@diyism Because lua-resty-mysql implements the SSL MySQL wire protocol and for that it needs the SSL cosocket support which only appears in ngx_lua 0.9.11+.

**Comment by agentzh** [comment]
Consider it resolved.

**Comment by lwtju** [comment]
this issue will appears when use ngx_stream_lua

**Comment by agentzh** [comment]
@lwtju Please open a new issue for ngx_stream_lua instead of hijacking this old closed issue.
