### ISSUE TITLE
When the openresty is running ,how to load the new lua file into the memory.

### ISSUE THREAD

**Issue by changjiasheng** [openresty/ngx_openresty#90]
I want load a lua file into the memory when the openresty is running,i did not need reload the nginx.

Much Thanks

**Comment by agentzh** [comment]
@changjiasheng Just use the `require` or `loadfile` Lua builtins in your Lua code. BTW, please use the openresty-en mailing list for such questions instead. Thank you. See http://openresty.org/#Community
