### ISSUE TITLE
怎么修改NGINX_VER

### ISSUE THREAD

**Issue by homichael** [openresty/ngx_openresty#93]
好吧,之前的问题已经解决了
但我在./configure之前,修改了bundle/nginx-1.7.10/src/core/nginx.h内的
#define NGINX_VER          "openresty/" NGINX_VERSION ".1"

修改为其他名字,但继续make,还是会覆盖为openresty.

**Comment by 7ai** [comment]
这个也没看到错误啊。。。。。

At 2015-04-11 18:19:54, "homichael" <notifications@github.com> wrote:


无论 32/64位,都通不过configure

yum install readline-devel pcre-devel openssl-devel pcre -y

wget http://openresty.org/download/ngx_openresty-1.7.10.1.tar.gz
tar zxvf ngx_openresty-1.7.10.1.tar.gz
cd ngx_openresty-1.7.10.1
./configure

checking for OS

Linux 2.6.32-431.23.3.el6.i686 i686 checking for C compiler ... found
using GNU C compiler
gcc version: 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) checking for gcc -pipe switch ... found checking for gcc builtin atomic operations ... found checking for C99 variadic macros ... found checking for gcc variadic macros ... found checking for unistd.h ... found checking for inttypes.h ... found checking for limits.h ... found checking for sys/filio.h ... not found checking for sys/param.h ... found checking for sys/mount.h ... found checking for sys/statvfs.h ... found checking for crypt.h ... found checking for Linux specific features checking for epoll ... found checking for EPOLLRDHUP ... found checking for O_PATH ... not found checking for sendfile() ... found checking for sendfile64() ... found checking for sys/prctl.h ... found checking for prctl(PR_SET_DUMPABLE) ... found checking for sched_setaffinity() ... found checking for crypt_r() ... found checking for sys/vfs.h ... found checking for nobody group ... found checking for poll() ... found checking for /dev/poll ... not found checking for kqueue ... not found checking for crypt() ... not found checking for crypt() in libcrypt ... found checking for F_READAHEAD ... not found checking for posix_fadvise() ... found checking for O_DIRECT ... found checking for F_NOCACHE ... not found checking for directio() ... not found checking for statfs() ... found checking for statvfs() ... found checking for dlopen() ... not found checking for dlopen() in libdl ... found checking for sched_yield() ... found checking for SO_SETFIB ... not found checking for SO_ACCEPTFILTER ... not found checking for TCP_DEFER_ACCEPT ... found checking for TCP_KEEPIDLE ... found checking for TCP_FASTOPEN ... not found checking for TCP_INFO ... found checking for accept4() ... found checking for int size ... 4 bytes checking for long size ... 4 bytes checking for long long size ... 8 bytes checking for void * size ... 4 bytes checking for uint64_t ... found checking for sig_atomic_t ... found checking for sig_atomic_t size ... 4 bytes checking for socklen_t ... found checking for in_addr_t ... found checking for in_port_t ... found checking for rlim_t ... found checking for uintptr_t ... uintptr_t found checking for system byte ordering ... little endian checking for size_t size ... 4 bytes checking for off_t size ... 8 bytes checking for time_t size ... 4 bytes checking for setproctitle() ... not found checking for pread() ... found checking for pwrite() ... found checking for sys_nerr ... found checking for localtime_r() ... found checking for posix_memalign() ... found checking for memalign() ... found checking for mmap(MAP_ANON|MAP_SHARED) ... found checking for mmap("/dev/zero", MAP_SHARED) ... found checking for System V shared memory ... found checking for POSIX semaphores ... not found checking for POSIX semaphores in libpthread ... found checking for struct msghdr.msg_control ... found checking for ioctl(FIONBIO) ... found checking for struct tm.tm_gmtoff ... found checking for struct dirent.d_namlen ... not found checking for struct dirent.d_type ... found checking for sysconf(_SC_NPROCESSORS_ONLN) ... found checking for openat(), fstatat() ... found checking for getaddrinfo() ... found checking for PCRE library ... found checking for PCRE JIT support ... not found checking for md5 in system md library ... not found checking for md5 in system md5 library ... not found checking for md5 in system OpenSSL crypto library ... found checking for sha1 in system md library ... not found checking for sha1 in system OpenSSL crypto library ... found checking for zlib library ... found creating objs/Makefile

Configuration summary

using system PCRE library
OpenSSL library is not used
md5: using system crypto library
sha1: using system crypto library

using system zlib library

nginx path prefix: "/usr/local/nginx"
nginx binary file: "/usr/local/nginx/sbin/nginx"
nginx configuration prefix: "/usr/local/nginx/conf"
nginx configuration file: "/usr/local/nginx/conf/nginx.conf"
nginx pid file: "/usr/local/nginx/logs/nginx.pid"
nginx error log file: "/usr/local/nginx/logs/error.log"
nginx http access log file: "/usr/local/nginx/logs/access.log"
nginx http client request body temporary files: "client_body_temp"
nginx http proxy temporary files: "proxy_temp"
nginx http fastcgi temporary files: "fastcgi_temp"
nginx http uwsgi temporary files: "uwsgi_temp"
nginx http scgi temporary files: "scgi_temp"

此处无法继续make.

**Comment by homichael** [comment]
那继续make, 出现这些提示
make[2]: Leaving directory `/test/ngx_openresty-1.7.10.1/build/nginx-1.7.10'
make -f objs/Makefile manpage
make[2]: Entering directory `/test/ngx_openresty-1.7.10.1/build/nginx-1.7.10'
sed -e "s|%%PREFIX%%|/usr/local/nginx|" \
		-e "s|%%PID_PATH%%|/usr/local/nginx/logs/nginx.pid|" \
		-e "s|%%CONF_PATH%%|/usr/local/nginx/conf/nginx.conf|" \
		-e "s|%%ERROR_LOG_PATH%%|/usr/local/nginx/logs/error.log|" \
		< man/nginx.8 > objs/nginx.8
make[2]: Leaving directory `/test/ngx_openresty-1.7.10.1/build/nginx-1.7.10'
make[1]: Leaving directory `/test/ngx_openresty-1.7.10.1/build/nginx-1.7.10'



然后查看并没有创建这个目录 /usr/local/nginx
ROOT权限执行的.

**Comment by lancelijade** [comment]
make install     ??

Lance

**Comment by agentzh** [comment]
@homichael Please, don't use Chinese here. This place is supposed to be English only. If you really want to use Chinese, please join the OpenResty (Chinese) mailing list instead. Please see http://openresty.org/#Community for more details. Thank you for your cooperation!
