### ISSUE TITLE
unable to include ngx_http_sub_module with --with-http_sub_module

### ISSUE THREAD

**Issue by max-l** [openresty/ngx_openresty#94]
I am compiling with 

./configure --with-luajit --with-http_sub_module 

make 
make install

and in my config file I call sub_filter,
and get the error message : unknown directive "sub_filter" when starting nginx

nginx -V does not show the sub_module in the module list : 

/usr/local/openresty/nginx/sbin/nginx -V

		
		nginx version: openresty/1.7.7.1
		built by gcc 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
		TLS SNI support enabled
		configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-I/tmp/ngx_openresty-1.7.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -O2' --add-module=../ngx_devel_kit-0.2.19 --add-module=../echo-nginx-module-0.57 --add-module=../xss-nginx-module-0.04 --add-module=../ngx_coolkit-0.2rc2 --add-module=../set-misc-nginx-module-0.27 --add-module=../form-input-nginx-module-0.10 --add-module=../encrypted-session-nginx-module-0.03 --add-module=../srcache-nginx-module-0.28 --add-module=../ngx_lua-0.9.13 --add-module=../ngx_lua_upstream-0.02 --add-module=../headers-more-nginx-module-0.25 --add-module=../array-var-nginx-module-0.03 --add-module=../memc-nginx-module-0.15 --add-module=../redis2-nginx-module-0.11 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.13 --add-module=../rds-csv-nginx-module-0.05 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/tmp/ngx_openresty-1.7.7.1/build/luajit-root/usr/local/openresty/luajit/lib' --with-http_ssl_module

in the configure file I see : 

Options directly inherited from nginx

 --with-http_sub_module             enable ngx_http_sub_module

**Comment by agentzh** [comment]
@max-l What are you suggesting here? Making http_sub_module the default in the OpenResty build? No, I don't want that :)

**Comment by max-l** [comment]
@agentzh,  I wasn't suggesting making --with-http_sub_module,   I was only wondering why adding "-with-http_sub_module" to the ./configure command was not adding the module. 

It turns out that the module *was* being added (the -with-http_sub_module switch was working correctly), it is just that I was calling the sub_filter directive inside an if statement in the nginx config (a syntax/format error), and I misinterpreted the error message as saying "this module is unknown", but it was really saying "the sub_filter directive cannot be used at this place in the config"...

So sorry, I should have closed this issue upon this discovery !

**Comment by agentzh** [comment]
@max-l No, the `sub_filter
