### ISSUE TITLE
About install nginx on mac X

### ISSUE THREAD

**Issue by jiajar** [openresty/ngx_openresty#96]
Hi agentzh ,

There, I have a problem when I make && install nginx .
When I execute make command,it always tell me that " ld: symbol(s) not found for architecture x86_64 "
I try reinstall   gcc on my mac , but it doesn't work .

**Comment by agentzh** [comment]
@jiajar Please follow the instructions (especially those for Mac OS X) here on the Installation page of the openresty site:

http://openresty.org/#Installation

In particular:

```
brew install pcre
 ./configure \
             --with-cc-opt="-I/usr/local/include" \
             --with-ld-opt="-L/usr/local/lib" -j4
make -j4
sudo make install
```

assuming you have 4 spare CPU logical cores in your machine ;)

**Comment by jiajar** [comment]
Thanks ! 
I should be more careful ！:-(
