### ISSUE TITLE
proxy_pass ssl v3

### ISSUE THREAD

**Issue by 6api** [openresty/ngx_openresty#97]
如果后端的网站是SSL V3，proxy_pass 将导致502错误
不知道作者什么时候升级到 nginx 1.8.0 可否解决这个问题

**Comment by agentzh** [comment]
@6api Please, no Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see http://openresty.org/#Community

Regarding your problem, I think you should explicitly enable SSLv3 in your ngx_proxy settings via the proxy_ssl_protocols directive:

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_protocols

As you can see, the default protocols exclude SSLv3.

BTW, SSLv3 is considered insecure by the industry and future nginx releases will remove it completely. Stick with the newer TLS protocols instead. Just my 2 cents.
