### ISSUE TITLE
ngx.var.server_name always gets first value when multiple values are defined

### ISSUE THREAD

**Issue by vdel26** [openresty/ngx_openresty#98]
I have an nginx.conf where I have a single server section that I want to use to catch all requests. In it I have a `server_name` with multiple names for the domains I am exposing. 

```nginx
server {
  server_name domain1.com domain2.com;
}
```

It would not be stricly necessary because by default it would already catch all requests, but I added it because I want to later check the value of the `server_name` that matched from Lua using `ngx.var.server_name`. 

What I am seeing is that in the Lua variable I always get domain1.com even if I send a request to domain2.com. I don't know whether this is expected and I should use separate server sections for this, or if there's something else I am doing wrong.

**Comment by dol** [comment]
What about ngx.var.http_host?

**Comment by agentzh** [comment]
@dol Yep, use of the nginx builtin variables `$host`, `$hostname`, and etc are recommended. `$server_name` is not for this purpose.

**Comment by zheng-ji** [comment]
this issue help me a lot,thanks to @agentzh

**Comment by bungle** [comment]
Should it still return a table with possibility of metamethod __tostring to return the first one?

**Comment by agentzh** [comment]
@bungle NGINX variables only take string-typed values.
